AWSTemplateFormatVersion: "2010-09-09"
Description: "SC Product - Lambda"

Parameters:
  FunctionName: { Type: String, Default: etl-producer }
  CodeS3Bucket: { Type: String }
  CodeS3Key:    { Type: String }
  Handler:      { Type: String, Default: handler.lambda_handler }
  Runtime:      { Type: String, Default: python3.12 }
  MemorySize:   { Type: Number, Default: 256 }
  Timeout:      { Type: Number, Default: 60 }

  UseVpc: { Type: String, AllowedValues: ["true","false"], Default: "false" }
  VpcIdParam: { Type: AWS::SSM::Parameter::Value<String>, Default: /core/vpc/id }
  PrivateSubnetAParam: { Type: AWS::SSM::Parameter::Value<String>, Default: /core/subnet/private/a }

  SqsQueueArn: { Type: String, Default: "" }

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaSg:
    Condition: UseVpcCond
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcIdParam
      GroupDescription: "Lambda SG"

  LambdaFn:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Role: !GetAtt LambdaRole.Arn
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Code: { S3Bucket: !Ref CodeS3Bucket, S3Key: !Ref CodeS3Key }
      MemorySize: !Ref MemorySize
      Timeout: !Ref Timeout
      VpcConfig: !If
        - UseVpcCond
        - { SubnetIds: [ !Ref PrivateSubnetAParam ], SecurityGroupIds: [ !Ref LambdaSg ] }
        - { Ref: "AWS::NoValue" }

  EventSource:
    Condition: HasSQS
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref SqsQueueArn
      FunctionName: !Ref LambdaFn
      Enabled: true
      BatchSize: 5

Conditions:
  UseVpcCond: !Equals [ !Ref UseVpc, "true" ]
  HasSQS:     !Not   [ !Equals [ !Ref SqsQueueArn, "" ] ]

Outputs:
  FunctionArn:  { Value: !GetAtt LambdaFn.Arn }
  FunctionName: { Value: !Ref LambdaFn }
