AWSTemplateFormatVersion: "2010-09-09"
Description: "Provision SC products for app domain (SNS, SQS, Lambda, Glue, StepFn, EventBridge)"

Parameters:
  Env:
    Type: String
    Default: dev

  SnsProductId:
    Type: String

  SqsProductId:
    Type: String

  LambdaProductId:
    Type: String

  GlueProductId:
    Type: String

  StepFnProductId:
    Type: String

  EvbProductId:
    Type: String

  # most SC products need a PA name, we hardcode to v1 (same as portfolio)
  ProvisioningArtifactName:
    Type: String
    Default: v1

  # if your products (e.g. lambda / glue) need VPC or subnets, you can pass SSM names here
  CoreVpcParam:
    Type: String
    Default: /core/vpc/id

  CorePrivateSubnetParam:
    Type: String
    Default: /core/subnet/private/a

  CorePublicSubnetParam:
    Type: String
    Default: /core/subnet/public/a

Resources:

  # 1) SNS
  ProvisionSns:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref SnsProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "sns-${Env}"
      ProvisioningParameters:
        - Key: TopicName
          Value: !Sub "sns-${Env}"

  # 2) SQS
  ProvisionSqs:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref SqsProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "sqs-${Env}"
      ProvisioningParameters:
        - Key: QueueName
          Value: !Sub "queue-${Env}"

  # 3) Lambda
  ProvisionLambda:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref LambdaProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "lambda-${Env}"
      ProvisioningParameters:
        - Key: FunctionName
          Value: !Sub "lambda-${Env}"
        - Key: CodeBucket
          Value: "my-cfn-artifacts-ap-south-1"
        - Key: CodeKey
          Value: "code/lambda_producer.zip"
        - Key: LambdaRoleArn
          Value: "arn:aws:iam::145411222814:role/ServiceCatalogProvisioningRole"

  # 4) Glue
  ProvisionGlue:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref GlueProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "glue-${Env}"
      ProvisioningParameters:
        - Key: GlueJobName
          Value: !Sub "glue-${Env}"
        - Key: ScriptLocation
          Value: "s3://my-cfn-artifacts-ap-south-1/code/elt_job.py"
        - Key: GlueRoleArn
          Value: "arn:aws:iam::145411222814:role/ServiceCatalogProvisioningRole"

  # 5) Step Functions
  ProvisionStepFn:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref StepFnProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "sfn-${Env}"
      ProvisioningParameters:
        - Key: StateMachineName
          Value: !Sub "sc-sfn-${Env}"
        - Key: RoleArn
          Value: "arn:aws:iam::145411222814:role/ServiceCatalogProvisioningRole"

  # 6) EventBridge
  ProvisionEventBridge:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductId: !Ref EvbProductId
      ProvisioningArtifactName: !Ref ProvisioningArtifactName
      ProvisionedProductName: !Sub "evb-${Env}"
      ProvisioningParameters:
        - Key: RuleName
          Value: !Sub "sc-every-5min-${Env}"
        - Key: ScheduleExpression
          Value: "rate(5 minutes)"

Outputs:
  SnsProvisionedId:
    Value: !Ref ProvisionSns
  SqsProvisionedId:
    Value: !Ref ProvisionSqs
  LambdaProvisionedId:
    Value: !Ref ProvisionLambda
  GlueProvisionedId:
    Value: !Ref ProvisionGlue
  StepFnProvisionedId:
    Value: !Ref ProvisionStepFn
  EvbProvisionedId:
    Value: !Ref ProvisionEventBridge