pipeline {
  agent any
  environment {
    AWS_DEFAULT_REGION = 'ap-south-1'
    ARTIFACT_BUCKET    = 'my-cfn-artifacts-ap-south-1'
    PORTFOLIO_STACK    = 'poc-data-portfolio-dev'
    LAUNCH_ROLE_ARN    = 'arn:aws:iam::145411222814:role/ServiceCatalogProvisioningRole'
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Zip Lambda code') {
      steps {
        sh '''
          set -e
          mkdir -p "$WORKSPACE/out"

          cd "$WORKSPACE/cloud/app-domain/code/lambda/producer"
          zip -rq "$WORKSPACE/out/lambda_producer.zip" .

          cd "$WORKSPACE/cloud/app-domain/code/lambda/consumer"
          zip -rq "$WORKSPACE/out/lambda_consumer.zip" .
        '''
      }
    }

    stage('Upload artifacts to S3') {
      steps {
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_default']]) {
          sh """
          aws s3 cp cloud/app-domain/products/product-sns-topic/product_template.yaml        s3://$ARTIFACT_BUCKET/products/product-sns-topic/product_template.yaml
          aws s3 cp cloud/app-domain/products/product-sqs-queue/product_template.yaml        s3://$ARTIFACT_BUCKET/products/product-sqs-queue/product_template.yaml
          aws s3 cp cloud/app-domain/products/product-lambda-fn/product_template.yaml        s3://$ARTIFACT_BUCKET/products/product-lambda-fn/product_template.yaml
          aws s3 cp cloud/app-domain/products/product-glue-job/product_template.yaml         s3://$ARTIFACT_BUCKET/products/product-glue-job/product_template.yaml
          aws s3 cp cloud/app-domain/products/product-stepfn/product_template.yaml           s3://$ARTIFACT_BUCKET/products/product-stepfn/product_template.yaml
          aws s3 cp cloud/app-domain/products/product-eventbridge-rule/product_template.yaml s3://$ARTIFACT_BUCKET/products/product-eventbridge-rule/product_template.yaml

          aws s3 cp "$WORKSPACE/out/lambda_producer.zip"  s3://$ARTIFACT_BUCKET/code/lambda_producer.zip
          aws s3 cp "$WORKSPACE/out/lambda_consumer.zip"  s3://$ARTIFACT_BUCKET/code/lambda_consumer.zip
          aws s3 cp cloud/app-domain/code/glue/elt_job.py s3://$ARTIFACT_BUCKET/code/elt_job.py
          """
        }
      }
    }

    stage('Deploy portfolio') {
      steps {
        script {
          // build URLs in Groovy first
          def snsUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-sns-topic/product_template.yaml"
          def sqsUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-sqs-queue/product_template.yaml"
          def lbdUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-lambda-fn/product_template.yaml"
          def gluUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-glue-job/product_template.yaml"
          def sfnUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-stepfn/product_template.yaml"
          def evbUrl = "https://s3.${env.AWS_DEFAULT_REGION}.amazonaws.com/${env.ARTIFACT_BUCKET}/products/product-eventbridge-rule/product_template.yaml"

          withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws_default']]) {
            sh """
            aws cloudformation deploy \
              --stack-name ${env.PORTFOLIO_STACK} \
              --template-file cloud/app-domain/portfolio/portfolio.yml \
              --parameter-overrides \
                LaunchRoleArn=${env.LAUNCH_ROLE_ARN} \
                UrlSns=${snsUrl} \
                UrlSqs=${sqsUrl} \
                UrlLbd=${lbdUrl} \
                UrlGlue=${gluUrl} \
                UrlStep=${sfnUrl} \
                UrlEvb=${evbUrl} \
              --capabilities CAPABILITY_NAMED_IAM
            """
          }
        }
      }
    }
  }
}
