AWSTemplateFormatVersion: "2010-09-09"
Description: "Service Catalog portfolio for data / app domain (SNS, SQS, Lambda, Glue, Step Functions, EventBridge)"

Parameters:
  LaunchRoleArn:
    Type: String
    Description: IAM role that Service Catalog will assume to launch the products

  UrlSns:
    Type: String
    Description: S3 URL to the SNS product_template.yaml

  UrlSqs:
    Type: String
    Description: S3 URL to the SQS product_template.yaml

  UrlLbd:
    Type: String
    Description: S3 URL to the Lambda product_template.yaml

  UrlGlue:
    Type: String
    Description: S3 URL to the Glue product_template.yaml

  UrlStep:
    Type: String
    Description: S3 URL to the Step Functions product_template.yaml

  UrlEvb:
    Type: String
    Description: S3 URL to the EventBridge Rule product_template.yaml

Resources:

  # 1) Portfolio
  DataPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: "Data/DE Components"
      Description: "Common data engineering components (SNS, SQS, Lambda, Glue, StepFn, EventBridge)"
      ProviderName: "Platform Team"

  # 2) Products (6 of them)

  SnsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "SNS Topic"
      Owner: "Platform Team"
      Description: "SNS topic for app/data events"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlSns
      SupportDescription: "Contact platform"
      SupportEmail: "platform@example.com"

  SqsProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "SQS Queue"
      Owner: "Platform Team"
      Description: "SQS queue for ingestion"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlSqs

  LambdaProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "Lambda Function"
      Owner: "Platform Team"
      Description: "Lambda function with S3-based code"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlLbd

  GlueProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "Glue Job"
      Owner: "Platform Team"
      Description: "Glue ETL/ELT job"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlGlue

  StepFnProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "Step Functions Workflow"
      Owner: "Platform Team"
      Description: "Simple state machine for data pipeline"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlStep

  EventBridgeProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: "EventBridge Rule"
      Owner: "Platform Team"
      Description: "EventBridge rule to trigger pipelines"
      ProvisioningArtifactParameters:
        - Name: "v1"
          Info:
            LoadTemplateFromURL: !Ref UrlEvb

  # 3) Associate all products to the portfolio

  AssocSns:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref SnsProduct

  AssocSqs:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref SqsProduct

  AssocLambda:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref LambdaProduct

  AssocGlue:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref GlueProduct

  AssocStepFn:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref StepFnProduct

  AssocEventBridge:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      ProductId:  !Ref EventBridgeProduct

  # 4) Give the launch role to the portfolio
  #    (so Service Catalog can actually launch these)

  PortfolioLaunchRole:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref DataPortfolio
      PrincipalARN: !Ref LaunchRoleArn
      PrincipalType: IAM

Outputs:
  PortfolioId:
    Description: "ID of the portfolio"
    Value: !Ref DataPortfolio

  SnsProductId:
    Description: "SNS product ID"
    Value: !Ref SnsProduct

  SqsProductId:
    Description: "SQS product ID"
    Value: !Ref SqsProduct

  LambdaProductId:
    Description: "Lambda product ID"
    Value: !Ref LambdaProduct

  GlueProductId:
    Description: "Glue product ID"
    Value: !Ref GlueProduct

  StepFnProductId:
    Description: "Step Functions product ID"
    Value: !Ref StepFnProduct

  EvbProductId:
    Description: "EventBridge product ID"
    Value: !Ref EventBridgeProduct