AWSTemplateFormatVersion: "2010-09-09"
Description: "SC Product - Create a simple AWS Glue Job (Spark) using script from S3"

Parameters:
  GlueJobName:
    Type: String
    Default: "sc-glue-demo-job"
    Description: Name of the Glue job to create

  GlueRoleArn:
    Type: String
    Description: IAM role ARN for the Glue job to run as
    # for PoC you can pass: arn:aws:iam::<ACCOUNT_ID>:role/AWSGlueServiceRole-Default

  ScriptLocation:
    Type: String
    Description: S3 location of the Glue script (s3://bucket/path/script.py)
    Default: "s3://my-cfn-artifacts-ap-south-1/code/elt_job.py"

  GlueVersion:
    Type: String
    Default: "4.0"
    AllowedValues:
      - "3.0"
      - "4.0"
    Description: Glue version

  NumberOfWorkers:
    Type: Number
    Default: 2
    Description: Number of workers

  WorkerType:
    Type: String
    Default: "G.1X"
    AllowedValues:
      - "Standard"
      - "G.1X"
      - "G.2X"
    Description: Glue worker type

Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref GlueJobName
      Role: !Ref GlueRoleArn
      GlueVersion: !Ref GlueVersion
      Command:
        Name: "glueetl"
        ScriptLocation: !Ref ScriptLocation
        PythonVersion: "3"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      WorkerType: !Ref WorkerType
      NumberOfWorkers: !Ref NumberOfWorkers
      Description: "Glue job created via Service Catalog product"
      DefaultArguments:
        "--job-language": "python"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"

Outputs:
  GlueJobNameOut:
    Description: Name of the Glue job created
    Value: !Ref GlueJob